language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
services:
- mysql
before_script:
- mysql --user=root --execute='CREATE DATABASE IF NOT EXISTS test;'
- mysql --user=root --execute='GRANT ALL ON test.* TO test@localhost;'
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: LMzXKva5eiuPHi3bZnVjj9b/oBBM04FFUg2tPDrnfkUe5tUmIv8nBJOQnJTNS0twS4rCFvnBVEC3D0ADWfwLCPYncRqQnXUt1P6quhmOYTv+nzMR/5qFhzTQfzPjtXzP8ej48TRMi8btKh+M1gXlDZ/KxEv3r2ez2DdTghnlI1k=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: DS2NwO+npBrU4JG6jNJ8f+vezExt55kxLMRfw32AFfYKL+FzB51RQNi/B7rOiDDnCVjiNKLaPphi/qzeWN8GMYjCnYZCxy88mXWPEpjsuUhDbDfX5eGPmnhFJkHjla7uo7RN2JHPNul2Ct8BUM09KJjhozJnGDiYCD7qr7TQK+4=
sudo: false
