language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
services:
- mysql
before_script:
- mysql --user=root --execute='CREATE DATABASE IF NOT EXISTS test;'
- mysql --user=root --execute='GRANT ALL ON test.* TO test@localhost;'
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: pgxA1BoST/L902/VJXAGCs5TB14SdqRBCOQyQjUyq6DJLNGWDnNsmfiWXjEwLJBRRMbCCNHf4bTEDL/GRs0ehQcIus46AWGTrb8Eizvbw7/5JmXc5gOMgJvb6i2tpV2gSEWXM2fT1PwfeQBnxIfTncpmDa0dBom9GtNjb6HJ4FI=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: DS2NwO+npBrU4JG6jNJ8f+vezExt55kxLMRfw32AFfYKL+FzB51RQNi/B7rOiDDnCVjiNKLaPphi/qzeWN8GMYjCnYZCxy88mXWPEpjsuUhDbDfX5eGPmnhFJkHjla7uo7RN2JHPNul2Ct8BUM09KJjhozJnGDiYCD7qr7TQK+4=
sudo: false
